# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mfinci/mycode/ga/rfsv3_slab_my

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mfinci/mycode/ga/rfsv3_slab_my

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mfinci/mycode/ga/rfsv3_slab_my/CMakeFiles /home/mfinci/mycode/ga/rfsv3_slab_my//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mfinci/mycode/ga/rfsv3_slab_my/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named router_feed_server

# Build rule for target.
router_feed_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 router_feed_server
.PHONY : router_feed_server

# fast build rule for target.
router_feed_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/build
.PHONY : router_feed_server/fast

#=============================================================================
# Target rules for targets named router_sim

# Build rule for target.
router_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 router_sim
.PHONY : router_sim

# fast build rule for target.
router_sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_sim.dir/build.make CMakeFiles/router_sim.dir/build
.PHONY : router_sim/fast

src/config_loader.o: src/config_loader.cpp.o
.PHONY : src/config_loader.o

# target to build an object file
src/config_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/config_loader.cpp.o
.PHONY : src/config_loader.cpp.o

src/config_loader.i: src/config_loader.cpp.i
.PHONY : src/config_loader.i

# target to preprocess a source file
src/config_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/config_loader.cpp.i
.PHONY : src/config_loader.cpp.i

src/config_loader.s: src/config_loader.cpp.s
.PHONY : src/config_loader.s

# target to generate assembly for a file
src/config_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/config_loader.cpp.s
.PHONY : src/config_loader.cpp.s

src/huge_page_region.o: src/huge_page_region.cpp.o
.PHONY : src/huge_page_region.o

# target to build an object file
src/huge_page_region.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/huge_page_region.cpp.o
.PHONY : src/huge_page_region.cpp.o

src/huge_page_region.i: src/huge_page_region.cpp.i
.PHONY : src/huge_page_region.i

# target to preprocess a source file
src/huge_page_region.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/huge_page_region.cpp.i
.PHONY : src/huge_page_region.cpp.i

src/huge_page_region.s: src/huge_page_region.cpp.s
.PHONY : src/huge_page_region.s

# target to generate assembly for a file
src/huge_page_region.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/huge_page_region.cpp.s
.PHONY : src/huge_page_region.cpp.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/net/tcp_client.o: src/net/tcp_client.cpp.o
.PHONY : src/net/tcp_client.o

# target to build an object file
src/net/tcp_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/tcp_client.cpp.o
.PHONY : src/net/tcp_client.cpp.o

src/net/tcp_client.i: src/net/tcp_client.cpp.i
.PHONY : src/net/tcp_client.i

# target to preprocess a source file
src/net/tcp_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/tcp_client.cpp.i
.PHONY : src/net/tcp_client.cpp.i

src/net/tcp_client.s: src/net/tcp_client.cpp.s
.PHONY : src/net/tcp_client.s

# target to generate assembly for a file
src/net/tcp_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/tcp_client.cpp.s
.PHONY : src/net/tcp_client.cpp.s

src/net/tcp_server.o: src/net/tcp_server.cpp.o
.PHONY : src/net/tcp_server.o

# target to build an object file
src/net/tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/tcp_server.cpp.o
.PHONY : src/net/tcp_server.cpp.o

src/net/tcp_server.i: src/net/tcp_server.cpp.i
.PHONY : src/net/tcp_server.i

# target to preprocess a source file
src/net/tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/tcp_server.cpp.i
.PHONY : src/net/tcp_server.cpp.i

src/net/tcp_server.s: src/net/tcp_server.cpp.s
.PHONY : src/net/tcp_server.s

# target to generate assembly for a file
src/net/tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/tcp_server.cpp.s
.PHONY : src/net/tcp_server.cpp.s

src/net/udp_server.o: src/net/udp_server.cpp.o
.PHONY : src/net/udp_server.o

# target to build an object file
src/net/udp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/udp_server.cpp.o
.PHONY : src/net/udp_server.cpp.o

src/net/udp_server.i: src/net/udp_server.cpp.i
.PHONY : src/net/udp_server.i

# target to preprocess a source file
src/net/udp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/udp_server.cpp.i
.PHONY : src/net/udp_server.cpp.i

src/net/udp_server.s: src/net/udp_server.cpp.s
.PHONY : src/net/udp_server.s

# target to generate assembly for a file
src/net/udp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/net/udp_server.cpp.s
.PHONY : src/net/udp_server.cpp.s

src/router_book.o: src/router_book.cpp.o
.PHONY : src/router_book.o

# target to build an object file
src/router_book.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/router_book.cpp.o
.PHONY : src/router_book.cpp.o

src/router_book.i: src/router_book.cpp.i
.PHONY : src/router_book.i

# target to preprocess a source file
src/router_book.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/router_book.cpp.i
.PHONY : src/router_book.cpp.i

src/router_book.s: src/router_book.cpp.s
.PHONY : src/router_book.s

# target to generate assembly for a file
src/router_book.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/router_book.cpp.s
.PHONY : src/router_book.cpp.s

src/threads/gap_thread.o: src/threads/gap_thread.cpp.o
.PHONY : src/threads/gap_thread.o

# target to build an object file
src/threads/gap_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/gap_thread.cpp.o
.PHONY : src/threads/gap_thread.cpp.o

src/threads/gap_thread.i: src/threads/gap_thread.cpp.i
.PHONY : src/threads/gap_thread.i

# target to preprocess a source file
src/threads/gap_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/gap_thread.cpp.i
.PHONY : src/threads/gap_thread.cpp.i

src/threads/gap_thread.s: src/threads/gap_thread.cpp.s
.PHONY : src/threads/gap_thread.s

# target to generate assembly for a file
src/threads/gap_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/gap_thread.cpp.s
.PHONY : src/threads/gap_thread.cpp.s

src/threads/io_thread.o: src/threads/io_thread.cpp.o
.PHONY : src/threads/io_thread.o

# target to build an object file
src/threads/io_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/io_thread.cpp.o
.PHONY : src/threads/io_thread.cpp.o

src/threads/io_thread.i: src/threads/io_thread.cpp.i
.PHONY : src/threads/io_thread.i

# target to preprocess a source file
src/threads/io_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/io_thread.cpp.i
.PHONY : src/threads/io_thread.cpp.i

src/threads/io_thread.s: src/threads/io_thread.cpp.s
.PHONY : src/threads/io_thread.s

# target to generate assembly for a file
src/threads/io_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/io_thread.cpp.s
.PHONY : src/threads/io_thread.cpp.s

src/threads/parser_thread.o: src/threads/parser_thread.cpp.o
.PHONY : src/threads/parser_thread.o

# target to build an object file
src/threads/parser_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/parser_thread.cpp.o
.PHONY : src/threads/parser_thread.cpp.o

src/threads/parser_thread.i: src/threads/parser_thread.cpp.i
.PHONY : src/threads/parser_thread.i

# target to preprocess a source file
src/threads/parser_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/parser_thread.cpp.i
.PHONY : src/threads/parser_thread.cpp.i

src/threads/parser_thread.s: src/threads/parser_thread.cpp.s
.PHONY : src/threads/parser_thread.s

# target to generate assembly for a file
src/threads/parser_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/parser_thread.cpp.s
.PHONY : src/threads/parser_thread.cpp.s

src/threads/thread_util.o: src/threads/thread_util.cpp.o
.PHONY : src/threads/thread_util.o

# target to build an object file
src/threads/thread_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/thread_util.cpp.o
.PHONY : src/threads/thread_util.cpp.o

src/threads/thread_util.i: src/threads/thread_util.cpp.i
.PHONY : src/threads/thread_util.i

# target to preprocess a source file
src/threads/thread_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/thread_util.cpp.i
.PHONY : src/threads/thread_util.cpp.i

src/threads/thread_util.s: src/threads/thread_util.cpp.s
.PHONY : src/threads/thread_util.s

# target to generate assembly for a file
src/threads/thread_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/threads/thread_util.cpp.s
.PHONY : src/threads/thread_util.cpp.s

src/time_util.o: src/time_util.cpp.o
.PHONY : src/time_util.o

# target to build an object file
src/time_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/time_util.cpp.o
.PHONY : src/time_util.cpp.o

src/time_util.i: src/time_util.cpp.i
.PHONY : src/time_util.i

# target to preprocess a source file
src/time_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/time_util.cpp.i
.PHONY : src/time_util.cpp.i

src/time_util.s: src/time_util.cpp.s
.PHONY : src/time_util.s

# target to generate assembly for a file
src/time_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_feed_server.dir/build.make CMakeFiles/router_feed_server.dir/src/time_util.cpp.s
.PHONY : src/time_util.cpp.s

tools/router_sim.o: tools/router_sim.cpp.o
.PHONY : tools/router_sim.o

# target to build an object file
tools/router_sim.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_sim.dir/build.make CMakeFiles/router_sim.dir/tools/router_sim.cpp.o
.PHONY : tools/router_sim.cpp.o

tools/router_sim.i: tools/router_sim.cpp.i
.PHONY : tools/router_sim.i

# target to preprocess a source file
tools/router_sim.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_sim.dir/build.make CMakeFiles/router_sim.dir/tools/router_sim.cpp.i
.PHONY : tools/router_sim.cpp.i

tools/router_sim.s: tools/router_sim.cpp.s
.PHONY : tools/router_sim.s

# target to generate assembly for a file
tools/router_sim.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/router_sim.dir/build.make CMakeFiles/router_sim.dir/tools/router_sim.cpp.s
.PHONY : tools/router_sim.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... router_feed_server"
	@echo "... router_sim"
	@echo "... src/config_loader.o"
	@echo "... src/config_loader.i"
	@echo "... src/config_loader.s"
	@echo "... src/huge_page_region.o"
	@echo "... src/huge_page_region.i"
	@echo "... src/huge_page_region.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/tcp_client.o"
	@echo "... src/net/tcp_client.i"
	@echo "... src/net/tcp_client.s"
	@echo "... src/net/tcp_server.o"
	@echo "... src/net/tcp_server.i"
	@echo "... src/net/tcp_server.s"
	@echo "... src/net/udp_server.o"
	@echo "... src/net/udp_server.i"
	@echo "... src/net/udp_server.s"
	@echo "... src/router_book.o"
	@echo "... src/router_book.i"
	@echo "... src/router_book.s"
	@echo "... src/threads/gap_thread.o"
	@echo "... src/threads/gap_thread.i"
	@echo "... src/threads/gap_thread.s"
	@echo "... src/threads/io_thread.o"
	@echo "... src/threads/io_thread.i"
	@echo "... src/threads/io_thread.s"
	@echo "... src/threads/parser_thread.o"
	@echo "... src/threads/parser_thread.i"
	@echo "... src/threads/parser_thread.s"
	@echo "... src/threads/thread_util.o"
	@echo "... src/threads/thread_util.i"
	@echo "... src/threads/thread_util.s"
	@echo "... src/time_util.o"
	@echo "... src/time_util.i"
	@echo "... src/time_util.s"
	@echo "... tools/router_sim.o"
	@echo "... tools/router_sim.i"
	@echo "... tools/router_sim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

